<?php
// $Id$
/**
 * @file
 *  Link ShURLy functionalities to services module.
 * @todo
 *  - add option to rate limit
 *  - add option for user api keys
 *  
 */

/**
 * Implementation of hook_perm().
 */
function shurly_service_perm() {
  $perms = array('administer short URL services');

  return $perms;
}

/**
 * Implementation of hook_menu().
 */

function shurly_service_menu() {
  $items = array();
  $items['shurly/api/shorten'] = array(
    'file'             => 'shurly_service.inc',
    'page callback'    => 'shurly_service_shorten',
    'access arguments' => array('Create short URLs'),
    'type'             => MENU_CALLBACK,
  );
  $items['shurly/api/expand'] = array(
    'file'             => 'shurly_service.inc',
    'page callback'    => 'shurly_service_expand',
    'access callback' => TRUE,
    'type'             => MENU_CALLBACK,
  );

  return $items;
}

