<?php
// $Id$
/**
 * @file
 *  Link ShURLy functionalities to services module.
 */

/**
 * Implementation of hook_perm().
 */
function shurly_service_perm() {
  $perms = array('administer short URL services');

  return $perms;
}

/**
 * Implementation of hook_menu().
 */

function search_service_menu() {
  $items = array();
  $items['shurly/api/shorten'] = array(
    'title'            => t('Search Service'),
    'description'      => t('Configure search service.'),
    'file'             => 'shurly_service.inc',
    'page callback'    => 'drupal_get_form',
    'access arguments' => array('Create short URLs'),
    'type'             => MENU_CALLBACK,
  );

  return $items;
}
